---
title: "assignment"
author: "Sridhar Iyengar"
date: "2024-03-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(purrr)
library(ggplot2)
library(roxygen2)
library(usethis)
library(devtools)
library(windturbine)

```



### Initializing Wind Turbines
```{r}
#wind = data.frame( c("A","B","C","D"),c(90, 150, 90, 150), c(2, 4, 6, 8))

source("C:/Users/Sridhar Iyengar/Documents/UCSB/Class/W24/windturbine/R/land_footprint.R")
windturbine::wind


wind <- read.csv("C:/Users/Sridhar Iyengar/Documents/UCSB/Class/W24/windturbine/wind.csv")
wind

colnames(wind) = c("tubrine_id","rotor_d","rated_pwr")

wind
```



### Using for loop to calculate land footprint
```{r}
landf1 = as.data.frame(matrix(nrow = 1, ncol = nrow(wind)))

colnames(landf1)=wind$tubrine_id

landf1

for (i in 1:nrow(wind)) {
  landf1[,i] = land_footprint(rd=wind$rotor_d[i], pwr = wind$rated_pwr[i])
}

landf1
```
### Using pmap to calculate land footprint
```{r}

landf2 = pmap(list(rd = wind$rotor_d, pwr = wind$rated_pwr), land_footprint)

landf2

landf2 = as.data.frame(landf2, col.names=wind$tubrine_id)

landf2

landf2l = landf2 %>% pivot_longer(cols = everything(), names_to = "turbine_id", values_to = "l_footprint")

landf2l

landf_plot = ggplot(landf2l, aes(x=turbine_id, y=l_footprint, fill=turbine_id))+geom_col()+labs(x="Turbine ID", y="Land Footprint (m2/GWh)", fill ="Turbine ID")+ggtitle("Land Footprint by Turbine ID")


landf_plot


sprintf("The turbine with the largest land footprint is turbine %s",landf2l$turbine_id[2])

```


### Testing & help documentation
```{r}

devtools::document()

help("land_footprint")


testthat::test_dir("test")

```

